Repository CharVstack/CharV-frontend, pull requests merged in 2022-12, with the labels that each got.

#58 CVS-122 VM の一覧表示
  package.json
  src/components/molecules/Columns/IconColumn/index.tsx
  src/components/molecules/Columns/index.ts
  src/components/organisms/Columns/StatusColumn/index.tsx
  src/components/organisms/Columns/index.ts
  src/components/organisms/Tables/InstanceTable/index.tsx
  src/components/organisms/Tables/index.ts
  src/pages/VMs/index.tsx
  yarn.lock
Labels: enhancement

#92 CVS-208 git-hooksの修正
  .github/workflows/cd.yaml
  package.json
Labels: enhancement

#94 CVS-200 self-hosted runner から github に runner の実行環境を移行
  .github/workflows/cd.yaml
Labels: enhancement

#98 CVS-200 ワークフローの修正
  .github/workflows/cd.yaml
Labels: bug

#97 CVS-209 github actionsの記法を変更
  .github/workflows/cd.yaml
  .github/workflows/code-test.yaml
  .github/workflows/review.yaml
  .github/workflows/storybook.yaml
Labels: refactoring

#103 CVS-211 prd 環境へのデプロイを作成
  .github/workflows/deploy-prd.yaml
  .github/workflows/deploy-stg.yaml
Labels: enhancement

#100 CVS-213 renovate enable automerge
  renovate.json
Labels: enhancement

#112 CVS-215 prd 環境へのデプロイイベントのトリガーを修正
  .github/workflows/deploy-prd.yaml
Labels: bug

#109 CVS-214 リリースノートに載せる authors から renovate を除外
  .github/release.yml
Labels: documentation

#45 CVS-142-フロントエンドからvmの操作
  .storybook/main.ts
  .storybook/preview.jsx
  src/components/organisms/Buttons/CreateNewVmButton.tsx
  src/components/organisms/Forms/CreateVm/CreateVmForm.stories.tsx
  src/components/organisms/Menu/VmControlMenu.spec.tsx
  src/components/organisms/Menu/VmControlMenu.stories.tsx
  src/components/organisms/Menu/VmControlMenu.tsx
  src/components/organisms/Tables/InstanceTable/InstanceTable.tsx
  src/lib/msw/handlers.ts
  src/pages/VMs/VMs.tsx
  tsconfig.json
  vite.config.ts
Labels: enhancement

#121 CVS-217 jsdomをhappy-domに戻す
  package.json
  vite.config.ts
  yarn.lock
Labels: refactoring

#119 CVS-213 RenovateでGitHubのautomergeを使う
  renovate.json
Labels: enhancement

#120 Feature/CVS-193 VM一覧でのカスタムフックのエラー処理
  .storybook/public/mockServiceWorker.js
  src/components/molecules/Columns/IconColumn/IconColumn.tsx
  src/components/organisms/Columns/StatusColumn/StatusColumn.tsx
  src/components/organisms/Dialogs/HookError/HookErrorDialog.tsx
  src/components/organisms/Dialogs/HookError/index.ts
  src/components/organisms/Dialogs/index.ts
  src/components/organisms/Tables/InstanceTable/InstanceTable.stories.tsx
  src/components/organisms/Tables/InstanceTable/InstanceTable.tsx
  src/lib/msw/handlers.ts
Labels: enhancement

#130 CVS-222 バンドルサイズの最適化
  package.json
  src/App.tsx
  src/components/molecules/Buttons/DeleteVmButton/DeleteVmButton.tsx
  src/components/molecules/Charts/Bar/BarChart.tsx
  src/components/molecules/Charts/Doughnut/DoughnutChart.tsx
  src/components/organisms/Dialogs/CreateVmDialog/CreateVmDialog.tsx
  src/components/organisms/Dialogs/HookError/HookErrorDialog.tsx
  src/pages/Home/Home.tsx
  src/pages/VMs/VMs.tsx
  src/styles/Theme.tsx
  src/utils/Routing.tsx
  src/utils/devtools/AtomsDevTools.tsx
  src/utils/devtools/DebugAtoms.tsx
  src/utils/devtools/HookForm.tsx
  vite.config.ts
  yarn.lock
Labels: bug, refactoring

#142 CVS-226 リファクタリング
  .eslintrc.js
  .github/workflows/storybook.yaml
  .storybook/main.ts
  package.json
  squoosh.ts
  src/App.tsx
  src/components/molecules/Charts/Bar/BarChart.tsx
  src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.tsx
  src/components/organisms/Cards/InstanceCards/HostStatusCard.tsx
  src/components/organisms/Cards/InstanceCards/HostStoragePoolCard.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.tsx
  src/components/organisms/Columns/StatusColumn/StatusColumn.tsx
  src/components/organisms/Dialogs/Error/ErrorDialog.stories.tsx
  src/components/organisms/Dialogs/Error/ErrorDialog.tsx
  src/components/organisms/Dialogs/Error/index.ts
  src/components/organisms/Dialogs/HookError/HookErrorDialog.tsx
  src/components/organisms/Dialogs/HookError/index.ts
  src/components/organisms/Dialogs/index.ts
  src/components/organisms/Drawers/SideBar/SideBar.stories.tsx
  src/components/organisms/Menu/VmControlMenu.tsx
  src/components/organisms/Tables/InstanceTable/InstanceTable.stories.tsx
  src/components/organisms/Tables/InstanceTable/InstanceTable.tsx
  src/hooks/api/v1.ts
  src/pages/ErrorPages/index.ts
  src/pages/Home/Home.tsx
  src/pages/Home/index.ts
  src/pages/VMs/index.ts
  src/pages/index.ts
  src/utils/Routing.tsx
  vite.config.ts
  yarn.lock
Labels: documentation, enhancement, refactoring

#144 CVS-229 ワークフローの修正
  .github/workflows/deploy-prd.yaml
  .github/workflows/deploy-stg.yaml
Labels: bug

#143 CVS-226 find-commentを修正
  .github/workflows/storybook.yaml
  src/components/molecules/Charts/Bar/BarChart.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
Labels: bug

#145 CVS-226 storybookのdelayを増やす
  .github/workflows/code-test.yaml
  .github/workflows/review.yaml
  .github/workflows/storybook.yaml
  renovate.json
  src/components/molecules/Charts/Bar/BarChart.stories.tsx
  src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
Labels: bug

#146 CVS-226 Chromaticからreg-suitに切り換え
  .github/workflows/code-test.yaml
  .github/workflows/reg-suit.yaml
  .github/workflows/review.yaml
  .github/workflows/storybook.yaml
  .gitignore
  package.json
  regconfig.json
  yarn.lock
Labels: enhancement

#152 CVS-226 もろもろ修正
  .github/workflows/reg-suit.yaml
  package.json
  regconfig.json
  src/components/molecules/Charts/Bar/BarChart.stories.tsx
  yarn.lock
Labels: bug

#153 CVS-226 reg-suitの許容誤差を変更
  package.json
  regconfig.json
Labels: bug

#154 CVS-226 mainでCIが落ちるのを修正
  .github/workflows/reg-suit.yaml
Labels: bug

#156 CVS-226 storycapの設定を調整
  .storybook/main.ts
  .storybook/preview.jsx
  package.json
  squoosh.ts
  src/components/molecules/Charts/Bar/BarChart.stories.tsx
  src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
  yarn.lock
Labels: bug

#157 CVS-226 storycapのdelayを増やす
  src/components/molecules/Charts/Doughnut/DoughnutChart.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
Labels: bug

#158 CVS-226 actionsにworkaroundを追加
  .github/workflows/reg-suit.yaml
Labels: bug
