Repository CharVstack/CharV-frontend, pull requests merged in 2022-11, with the labels that each got.

#43 CVS-151 開発ルールの整備
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
Labels: documentation

#44 CVS-155 リリースノートの設定ファイルの作成
  .github/release.yml
Labels: documentation

#47 CVS-165 aspidaを依存に含める
  package.json
  yarn.lock
Labels: bug

#49 CVS-179 Storybookの参考ファイルを作成
  .eslintrc.js
  .github/workflows/review.yaml
  .gitignore
  .storybook/main.js
  .storybook/preview.jsx
  package.json
  src/components/atoms/Headings/H1.stories.tsx
  src/components/atoms/Headings/H2.stories.tsx
  src/components/atoms/Headings/H3.stories.tsx
  src/components/atoms/Headings/H4.stories.tsx
  src/components/atoms/Headings/H5.stories.tsx
  src/components/atoms/Headings/H6.stories.tsx
  src/styles/Theme.tsx
  vite.config.ts
  yarn.lock
Labels: documentation, enhancement

#51 CVS-181 mswのセットアップ
  .eslintrc.js
  .prettierignore
  .storybook/main.js
  .storybook/main.ts
  .storybook/preview.jsx
  .storybook/public/mockServiceWorker.js
  package.json
  src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx
  src/lib/msw/browser.ts
  src/lib/msw/handlerFactory.ts
  src/lib/msw/handlers.ts
  src/lib/msw/server.ts
  src/pages/Home/index.tsx
  vitest.setup.ts
  yarn.lock
Labels: documentation, enhancement

#53 CVS-182 Github Pagesにassetsを含める
  .storybook/main.ts
  package.json
  yarn.lock
Labels: documentation, enhancement

#54 CVS-183 codecovを使う
  .c8rc.json
  .github/workflows/code-test.yaml
  README.md
  package.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#55 CVS-182 github pagesでstorybookが壊れるのを直す
  .storybook/preview.jsx
  package.json
Labels: bug, documentation

#56 CVS-182 mswのパスを修正
  .storybook/preview.jsx
  package.json
Labels: bug, documentation

#57 CVS-182 ローカルでstorybookが動かないのを修正
  .storybook/preview.jsx
Labels: bug, documentation

#59 CVS-184 storybookをある程度追加
  .prettierignore
  package.json
  src/components/molecules/Card/Card.stories.tsx
  src/components/molecules/Card/Card.tsx
  src/components/molecules/Card/CardAsideContent.stories.tsx
  src/components/molecules/Card/CardAsideContent.tsx
  src/components/molecules/Card/CardContent.tsx
  src/components/molecules/Card/CardProps.tsx
  src/components/molecules/Card/CardTitle.stories.tsx
  src/components/molecules/Card/CardTitle.tsx
  src/components/molecules/Card/index.ts
  src/components/molecules/Cards/InstanceCard/InstanceCard.tsx
  src/components/molecules/Cards/InstanceCard/InstanceCardProps.tsx
  src/components/molecules/Cards/index.ts
  src/components/molecules/Progress/Circular/LoadingSpinner.stories.tsx
  src/components/molecules/Tabs/CreateVm/tabPanel.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostMemoryCard.tsx
  src/components/organisms/Cards/InstanceCards/HostStatusCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostStatusCard.tsx
  src/components/organisms/Cards/InstanceCards/HostStoragePoolCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/HostStoragePoolCard.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.stories.tsx
  src/components/organisms/Cards/InstanceCards/RunningVmsCard.tsx
Labels: documentation
